version: 0.0
os: linux
files:
  - source: /               # Deploy ALL files
    destination: /var/www/avsconsultant.com/public_html
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  AfterInstall:
    - location: scripts/start_server.sh
    - location: scripts/permissions.sh   # New script for file permissions